-- ============================================================
-- طرف الخيط — لوحة شرف الداعمين
-- شغّل الملف مرة واحدة في Supabase SQL Editor
-- ============================================================

create table if not exists public.supporters (
  id bigint generated by default as identity primary key,
  supporter_name text not null check (char_length(trim(supporter_name)) between 2 and 40),
  payment_method text not null check (payment_method in ('vodafone_cash','instapay')),
  reference_note text,
  amount numeric(10,2),
  consent_public boolean not null default true,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  approved_at timestamptz
);

alter table public.supporters enable row level security;

-- لا نسمح للـanon بالقراءة المباشرة من الجدول أو تعديل الحالات.
revoke all on public.supporters from anon, authenticated;

create or replace function public.submit_supporter(
  p_supporter_name text,
  p_payment_method text,
  p_reference_note text default null,
  p_amount numeric default null,
  p_consent_public boolean default true
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text := regexp_replace(trim(coalesce(p_supporter_name,'')), '\s+', ' ', 'g');
  v_method text := lower(trim(coalesce(p_payment_method,'')));
  v_ref text := nullif(left(trim(coalesce(p_reference_note,'')),120),'');
begin
  if char_length(v_name) < 2 or char_length(v_name) > 40 then return false; end if;
  if v_method not in ('vodafone_cash','instapay') then return false; end if;
  if p_amount is not null and (p_amount <= 0 or p_amount > 1000000) then return false; end if;

  insert into public.supporters(supporter_name,payment_method,reference_note,amount,consent_public,status)
  values (left(v_name,40),v_method,v_ref,p_amount,coalesce(p_consent_public,true),'pending');
  return true;
exception when others then
  return false;
end;
$$;

grant execute on function public.submit_supporter(text,text,text,numeric,boolean) to anon, authenticated;

create or replace function public.get_supporters_wall(p_limit int default 100)
returns table(
  supporter_name text,
  payment_method text,
  approved_at timestamptz
)
language sql
security definer
set search_path = public
stable
as $$
  select s.supporter_name, s.payment_method, coalesce(s.approved_at,s.created_at)
  from public.supporters s
  where s.status='approved' and s.consent_public=true
  order by coalesce(s.approved_at,s.created_at) desc
  limit greatest(1,least(coalesce(p_limit,100),200));
$$;

grant execute on function public.get_supporters_wall(int) to anon, authenticated;

-- المراجعة تتم من Supabase Dashboard بأمان:
-- Table Editor > supporters > غيّر status إلى approved
-- ويمكن وضع approved_at = now().
